function Module_Card_NPC_Wyvern::Ass_Load(%this)
{

%this.Ass_Image_Icon=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_Icon");

%this.Ass_Animation_Icon="Module_Card_NPC_Wyvern:Animation_Icon";

%this.Ass_Image_NPC_Wyvern_Explosion=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Explosion");

%this.Ass_Image_NPC_Wyvern_Fire_Ball=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Fire_Ball");

%this.Ass_Image_NPC_Wyvern_Breath_Down=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Breath_Down");

%this.Ass_Image_NPC_Wyvern_Breath_Down_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Breath_Down_Left");

%this.Ass_Image_NPC_Wyvern_Breath_Down_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Breath_Down_Right");

%this.Ass_Image_NPC_Wyvern_Breath_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Breath_Left");

%this.Ass_Image_NPC_Wyvern_Breath_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Breath_Right");

%this.Ass_Image_NPC_Wyvern_Breath_Up=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Breath_Up");

%this.Ass_Image_NPC_Wyvern_Breath_Up_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Breath_Up_Left");

%this.Ass_Image_NPC_Wyvern_Breath_Up_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Breath_Up_Right");

%this.Ass_Image_NPC_Wyvern_Die_Down=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Die_Down");

%this.Ass_Image_NPC_Wyvern_Die_Down_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Die_Down_Left");

%this.Ass_Image_NPC_Wyvern_Die_Down_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Die_Down_Right");

%this.Ass_Image_NPC_Wyvern_Die_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Die_Left");

%this.Ass_Image_NPC_Wyvern_Die_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Die_Right");

%this.Ass_Image_NPC_Wyvern_Die_Up=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Die_Up");

%this.Ass_Image_NPC_Wyvern_Die_Up_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Die_Up_Left");

%this.Ass_Image_NPC_Wyvern_Die_Up_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Die_Up_Right");

%this.Ass_Image_NPC_Wyvern_Fly_Down=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Fly_Down");

%this.Ass_Image_NPC_Wyvern_Fly_Down_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Fly_Down_Left");

%this.Ass_Image_NPC_Wyvern_Fly_Down_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Fly_Down_Right");

%this.Ass_Image_NPC_Wyvern_Fly_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Fly_Left");

%this.Ass_Image_NPC_Wyvern_Fly_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Fly_Right");

%this.Ass_Image_NPC_Wyvern_Fly_Up=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Fly_Up");

%this.Ass_Image_NPC_Wyvern_Fly_Up_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Fly_Up_Left");

%this.Ass_Image_NPC_Wyvern_Fly_Up_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Fly_Up_Right");

%this.Ass_Image_NPC_Wyvern_Hit_Down=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hit_Down");

%this.Ass_Image_NPC_Wyvern_Hit_Down_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hit_Down_Left");

%this.Ass_Image_NPC_Wyvern_Hit_Down_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hit_Down_Right");

%this.Ass_Image_NPC_Wyvern_Hit_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hit_Left");

%this.Ass_Image_NPC_Wyvern_Hit_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hit_Right");

%this.Ass_Image_NPC_Wyvern_Hit_Up=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hit_Up");

%this.Ass_Image_NPC_Wyvern_Hit_Up_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hit_Up_Left");

%this.Ass_Image_NPC_Wyvern_Hit_Up_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hit_Up_Right");

%this.Ass_Image_NPC_Wyvern_Hover_Down=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hover_Down");

%this.Ass_Image_NPC_Wyvern_Hover_Down_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hover_Down_Left");

%this.Ass_Image_NPC_Wyvern_Hover_Down_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hover_Down_Right");

%this.Ass_Image_NPC_Wyvern_Hover_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hover_Left");

%this.Ass_Image_NPC_Wyvern_Hover_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hover_Right");

%this.Ass_Image_NPC_Wyvern_Hover_Up=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hover_Up");

%this.Ass_Image_NPC_Wyvern_Hover_Up_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hover_Up_Left");

%this.Ass_Image_NPC_Wyvern_Hover_Up_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Hover_Up_Right");

%this.Ass_Image_NPC_Wyvern_Ram_Down=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Ram_Down");

%this.Ass_Image_NPC_Wyvern_Ram_Down_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Ram_Down_Left");

%this.Ass_Image_NPC_Wyvern_Ram_Down_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Ram_Down_Right");

%this.Ass_Image_NPC_Wyvern_Ram_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Ram_Left");

%this.Ass_Image_NPC_Wyvern_Ram_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Ram_Right");

%this.Ass_Image_NPC_Wyvern_Ram_Up=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Ram_Up");

%this.Ass_Image_NPC_Wyvern_Ram_Up_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Ram_Up_Left");

%this.Ass_Image_NPC_Wyvern_Ram_Up_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Ram_Up_Right");

%this.Ass_Image_NPC_Wyvern_Sting_Down=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Sting_Down");

%this.Ass_Image_NPC_Wyvern_Sting_Down_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Sting_Down_Left");

%this.Ass_Image_NPC_Wyvern_Sting_Down_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Sting_Down_Right");

%this.Ass_Image_NPC_Wyvern_Sting_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Sting_Left");

%this.Ass_Image_NPC_Wyvern_Sting_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Sting_Right");

%this.Ass_Image_NPC_Wyvern_Sting_Up=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Sting_Up");

%this.Ass_Image_NPC_Wyvern_Sting_Up_Left=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Sting_Up_Left");

%this.Ass_Image_NPC_Wyvern_Sting_Up_Right=AssetDatabase.acquireAsset("Module_Card_NPC_Wyvern:Image_NPC_Wyvern_Sting_Up_Right");

}
