function Module_Player_Sprite_Gill_Balentine::Ass_Load(%this)
{

%this.Ass_Image_Gill_Balentine_Attack_Down=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Attack_Down");
%this.Ass_Image_Gill_Balentine_Attack_Down_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Attack_Down_Left");
%this.Ass_Image_Gill_Balentine_Attack_Down_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Attack_Down_Right");
%this.Ass_Image_Gill_Balentine_Attack_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Attack_Left");
%this.Ass_Image_Gill_Balentine_Attack_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Attack_Right");
%this.Ass_Image_Gill_Balentine_Attack_Up=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Attack_Up");
%this.Ass_Image_Gill_Balentine_Attack_Up_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Attack_Up_Left");
%this.Ass_Image_Gill_Balentine_Attack_Up_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Attack_Up_Right");

%this.Ass_Image_Gill_Balentine_Emote_Talk_Down=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Emote_Talk_Down");
%this.Ass_Image_Gill_Balentine_Emote_Talk_Down_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Emote_Talk_Down_Left");
%this.Ass_Image_Gill_Balentine_Emote_Talk_Down_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Emote_Talk_Down_Right");
%this.Ass_Image_Gill_Balentine_Emote_Talk_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Emote_Talk_Left");
%this.Ass_Image_Gill_Balentine_Emote_Talk_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Emote_Talk_Right");
%this.Ass_Image_Gill_Balentine_Emote_Talk_Up=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Emote_Talk_Up");
%this.Ass_Image_Gill_Balentine_Emote_Talk_Up_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Emote_Talk_Up_Left");
%this.Ass_Image_Gill_Balentine_Emote_Talk_Up_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Emote_Talk_Up_Right");

%this.Ass_Image_Gill_Balentine_Run_Down=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Run_Down");
%this.Ass_Image_Gill_Balentine_Run_Down_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Run_Down_Left");
%this.Ass_Image_Gill_Balentine_Run_Down_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Run_Down_Right");
%this.Ass_Image_Gill_Balentine_Run_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Run_Left");
%this.Ass_Image_Gill_Balentine_Run_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Run_Right");
%this.Ass_Image_Gill_Balentine_Run_Up=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Run_Up");
%this.Ass_Image_Gill_Balentine_Run_Up_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Run_Up_Left");
%this.Ass_Image_Gill_Balentine_Run_Up_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Run_Up_Right");

%this.Ass_Image_Gill_Balentine_Stand_Down=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Stand_Down");
%this.Ass_Image_Gill_Balentine_Stand_Down_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Stand_Down_Left");
%this.Ass_Image_Gill_Balentine_Stand_Down_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Stand_Down_Right");
%this.Ass_Image_Gill_Balentine_Stand_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Stand_Left");
%this.Ass_Image_Gill_Balentine_Stand_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Stand_Right");
%this.Ass_Image_Gill_Balentine_Stand_Up=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Stand_Up");
%this.Ass_Image_Gill_Balentine_Stand_Up_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Stand_Up_Left");
%this.Ass_Image_Gill_Balentine_Stand_Up_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gill_Balentine:Image_Gill_Balentine_Stand_Up_Right");

}
