function Module_Card_Summon_Unit::Ass_Load(%this)
{

%this.Ass_Image_Icon=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Icon");

%this.Ass_Animation_Icon="Module_Card_Summon_Unit:Animation_Icon";

%this.Ass_Image_Summon_Unit_Attack_Down=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Attack_Down");
%this.Ass_Image_Summon_Unit_Attack_Down_Left=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Attack_Down_Left");
%this.Ass_Image_Summon_Unit_Attack_Down_Right=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Attack_Down_Right");
%this.Ass_Image_Summon_Unit_Attack_Left=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Attack_Left");
%this.Ass_Image_Summon_Unit_Attack_Right=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Attack_Right");
%this.Ass_Image_Summon_Unit_Attack_Up=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Attack_Up");
%this.Ass_Image_Summon_Unit_Attack_Up_Left=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Attack_Up_Left");
%this.Ass_Image_Summon_Unit_Attack_Up_Right=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Attack_Up_Right");

%this.Ass_Image_Summon_Unit_Run_Down=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Run_Down");
%this.Ass_Image_Summon_Unit_Run_Down_Left=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Run_Down_Left");
%this.Ass_Image_Summon_Unit_Run_Down_Right=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Run_Down_Right");
%this.Ass_Image_Summon_Unit_Run_Left=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Run_Left");
%this.Ass_Image_Summon_Unit_Run_Right=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Run_Right");
%this.Ass_Image_Summon_Unit_Run_Up=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Run_Up");
%this.Ass_Image_Summon_Unit_Run_Up_Left=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Run_Up_Left");
%this.Ass_Image_Summon_Unit_Run_Up_Right=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Run_Up_Right");

%this.Ass_Image_Summon_Unit_Stand_Down=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Stand_Down");
%this.Ass_Image_Summon_Unit_Stand_Down_Left=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Stand_Down_Left");
%this.Ass_Image_Summon_Unit_Stand_Down_Right=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Stand_Down_Right");
%this.Ass_Image_Summon_Unit_Stand_Left=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Stand_Left");
%this.Ass_Image_Summon_Unit_Stand_Right=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Stand_Right");
%this.Ass_Image_Summon_Unit_Stand_Up=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Stand_Up");
%this.Ass_Image_Summon_Unit_Stand_Up_Left=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Stand_Up_Left");
%this.Ass_Image_Summon_Unit_Stand_Up_Right=AssetDatabase.acquireAsset("Module_Card_Summon_Unit:Image_Summon_Unit_Stand_Up_Right");

}
