function Module_Player_Sprite_Gigi_32x32::Ass_Load(%this)
{

%this.Ass_Image_Gigi_32x32_Stand_Down=AssetDatabase.acquireAsset("Module_Player_Sprite_Gigi_32x32:Image_Gigi_32x32_Stand_Down");

%this.Ass_Image_Gigi_32x32_Stand_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gigi_32x32:Image_Gigi_32x32_Stand_Left");

%this.Ass_Image_Gigi_32x32_Stand_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gigi_32x32:Image_Gigi_32x32_Stand_Right");

%this.Ass_Image_Gigi_32x32_Stand_Up=AssetDatabase.acquireAsset("Module_Player_Sprite_Gigi_32x32:Image_Gigi_32x32_Stand_Up");

%this.Ass_Image_Gigi_32x32_Run_Down=AssetDatabase.acquireAsset("Module_Player_Sprite_Gigi_32x32:Image_Gigi_32x32_Run_Down");

%this.Ass_Image_Gigi_32x32_Run_Left=AssetDatabase.acquireAsset("Module_Player_Sprite_Gigi_32x32:Image_Gigi_32x32_Run_Left");

%this.Ass_Image_Gigi_32x32_Run_Right=AssetDatabase.acquireAsset("Module_Player_Sprite_Gigi_32x32:Image_Gigi_32x32_Run_Right");

%this.Ass_Image_Gigi_32x32_Run_Up=AssetDatabase.acquireAsset("Module_Player_Sprite_Gigi_32x32:Image_Gigi_32x32_Run_Up");

}
